# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c788003290a21f89f8c934c18ae064dc81dc15cfe611897993aea41f83c35bfc883d83d4ee57bfe7f5d8c444c52b8024c680155113f69c5f55ddfb89faa5712a

test:
  secret_key_base: 31a33bdc3bf91e5fb377862962348b6150902fd55e2ff5869940cb339574efd90494c5d27a8a2ef8e8cadab8900a8527ed605f456968c311a76a33d8b2cf9fa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
